apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-pvc
  labels:
    app: fio-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  # storageClassName: longhorn
  storageClassName: openebs-localpv
---
apiVersion: v1
kind: Pod
metadata:
  name: fio-pod
  labels:
    app: fio-test
spec:
  containers:
    - name: fio-container
      image: ghcr.io/vtarmo/disktest:main
      command: ["/bin/sh", "-c", "tail -f /dev/null"]
      volumeMounts:
        - mountPath: /testvol
          name: fio-volume
  volumes:
    - name: fio-volume
      persistentVolumeClaim:
        claimName: fio-pvc
  restartPolicy: Never
